### ISSUE TITLE
Ugly toolbar in Atril after update from 1.16 to 1.18

### ISSUE THREAD

**Issue by Photon89** [oberon2007/vertex-maia-themes#5] opened 2017-03-30 12:42 UTC
After today's update from Atril 1.16 to 1.18 (1.17 has been skipped by the repos of Arch Linux), the tool bar has an ugly black border and the elements are dark, see attached screenshots. 
![funktionalableitung pdf_045](https://cloud.githubusercontent.com/assets/1191480/24503628/2c3fd5a4-1553-11e7-8452-92687ef2b496.png)
![funktionalableitung pdf_044](https://cloud.githubusercontent.com/assets/1191480/24503629/2c426b20-1553-11e7-9a1b-f1e538ed9fc5.png)

Atril's devs told me that this is a theme related issue, see here for more information: https://github.com/mate-desktop/atril/issues/249

**Comment by oberon-manjaro** [comment] 2017-03-31 00:01
Working on it... :wink: This gtk3 stuff is tedious... but already looking a bit better:

![](http://imgur.com/gwGNzpn.png)
___
Sofar I was at least able to fix the dark frame around the toolbar. Will try tomorrow if I can find the right properties to fix the button and entrybox colors, too. The text near the buttons is also not nice, sigh...!

**Comment by oberon-manjaro** [comment] 2017-03-31 01:03
![](http://imgur.com/tNOXX4r.png)

:stuck_out_tongue:

**Comment by Photon89** [comment] 2017-03-31 09:21
Looks nice, thanks! I think, I will put a vertex-maia-themes-git package to the AUR to be able to test it without waiting for the fixes to arrive in testing. Will report back soon!

**Comment by Photon89** [comment] 2017-03-31 09:38
Actually, I am a bit puzzled which git repo vertex-maia is actually hosted in. This repo has been last updated a year ago. The repo the fixing commit went to is vertex, not vertex-maia...

**Comment by oberon-manjaro** [comment] 2017-03-31 09:56
Wait until I'm done with the repair... :wink: Have a look at the PKGBUILD in our community repo! In this repo here there are just some additional files. The theme itself we've been pulling from upstream and changing the colors with the PKGBUILD. Recently some additional patches were also needed since upstream doesn't fix stuff anymore. I've now forked the theme and will apply our fixes there...

**Comment by Photon89** [comment] 2017-03-31 10:39
Thanks, I see! I assume that this complex handling is for the fork to keep compatibility to the original Vertex theme and get all the fixes from it, right? Wouldn't it be easier to have a proper fork with all the -maia changes applied directly to the fork and then pull the changes from the original vertex theme whenever there are some: https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/ ? Or is there a high probability that the merges will lead to conflicts if the fork deviates from the base too much? 

Anyway, I built the community PKGBUILD and it looks somewhat between your first and second screenshot, I guess, you didn't push the latest changes yet. But I am ready to test, when everything is pushed! :)

**Comment by oberon-manjaro** [comment] 2017-03-31 12:42
Thing is that we apply the color changes AFTER the theme is compiled - not a clean solution but it looked like a good way to do it at that time. If you want to apply the adjustments to the sourcecode you'd have to do it differently but noone ever found the time to do that. It's not trivial and with gtk3 anyway you don't know if you will have to write a completely new theme with the next gtk update anyway... 😉 So we just left it like that.
Since upstream doesn't appear to merge fixes anymore I began to apply them as patches a while ago but it's already getting a bit messy... Now I will just push them directly to my fork. In case there are upstream updates it's no problem to merge them of course.
If you want to try the latest changes you can simply change source in the PKGBUILD to point to my account instead of the upstream one...

**Comment by Photon89** [comment] 2017-03-31 13:11
> If you want to try the latest changes you can simply change source in the PKGBUILD to point to my account instead of the upstream one...

Do you mean this repo: https://github.com/oberon2007/vertex-theme? This is what I did, but it still has the black zoom level button with white text on it and also hard to read white text on the white "Back" and "Next" buttons...

**Comment by oberon-manjaro** [comment] 2017-03-31 13:40
Yes, that's what I meant when I wrote
> Sofar I was at least able to fix the dark frame around the toolbar. Will try tomorrow if I can find the right properties to fix the button and entrybox colors, too. The text near the buttons is also not nice, sigh...!

and
> Wait until I'm done with the repair...

😉

**Comment by Photon89** [comment] 2017-03-31 13:58
Sorry, misunderstanding on my side. Then I'm keeping quiet and waiting. 😄

**Comment by oberon-manjaro** [comment] 2017-04-01 03:00
All fixed now 😝 I hate gtk3! 😜 

![](http://imgur.com/CfJ8ZDL.png)

**Closed as completed by oberon-manjaro** 2017-04-01 03:00 UTC

**Comment by Photon89** [comment] 2017-04-01 06:23
Thanks! There is just one minor thing left (it is actually visible on your screenshot as well): The font on the "Previous" and "Next" buttons is blurred (but it gets good again if you hover the button).

**Comment by oberon-manjaro** [comment] 2017-04-01 09:04
I normally don't use the light version of the theme, but that's how I know the font also from elsewhere, like:

![](http://imgur.com/wOMtlPy.png)

My font settings are not optimized with this setup, also ...
In any case I don't think this has to do with this issue here, maybe not even with the theme.

**Comment by Photon89** [comment] 2017-04-01 10:48
As far as I understand, the blurred font is used in inactive buttons (for example, if no file is loaded or the last page is reached). So the issue is just that the blurred font is used on active buttons rather than inactive ones.

**Comment by oberon-manjaro** [comment] 2017-04-01 16:49
The font is maybe not good but I would not really call it blurred. If you look at the [commit](https://github.com/oberon2007/vertex-theme/commit/dc1a5255854ff6bbacacfda28db0770c1292c2b6). The disabled label now just uses the same property as ``button:disabled:active > label`` in other context. So you could say text styling is as it was intended by the author of the original vertex theme.
It will also look different with any other font you use and will depend on your system's overall font rendering.
Here's with Comfortaa for example:

![](http://imgur.com/FwJcuLPl.png)

**Comment by Photon89** [comment] 2017-04-01 19:34
I think, I figured it out, it is necessary to remove line 692 (text shadow). One can add a text shadow for the inactive buttons (some themes have it, some don't, a matter of taste), but there should be no text shadow for active buttons. 😄 

edit: No, sorry, I looked in the button at the wrong state, give me some more time.

**Comment by oberon-manjaro** [comment] 2017-04-01 19:46
I think the property we are talking about is button:disabled:active

**Comment by oberon-manjaro** [comment] 2017-04-01 19:48
``> label`` ! 😉

**Comment by oberon-manjaro** [comment] 2017-04-01 19:49
Although it doesn't look like a shadow to me. More as if it sould be bold text.

**Comment by oberon-manjaro** [comment] 2017-04-01 19:51
I think it looks the same as this, for example in my firefox:

![](http://imgur.com/dVqGvbV.png)

**Comment by Photon89** [comment] 2017-04-01 19:58
Maybe you are right. It reminded me of this shadow text style some old GTK2 themes had on disabled buttons, like: http://imgur.com/wwQEQid But it might well be that it is now done through bold text in Vertex-Maia...

**Comment by oberon-manjaro** [comment] 2017-04-01 20:01
"bold" has only one occurrance in line 1196. Commenting it out makes no difference.
gtk3 theming is just a nightmare 😆

**Comment by oberon-manjaro** [comment] 2017-04-01 20:03
I think the example in your screenshot was a shadow problem, yes.

**Comment by Photon89** [comment] 2017-04-01 20:08
I wouldn't call it a problem, this is how things were styled back then. 😃 This shadowy text only appeared when the button is inactive (not clickable), when the button is clickable the text has no shadow. Whereas what we have in Vertex-Maia is that the text is "strange" - be it a shadow or a bold font - when the button is clickable and becomes normal when it is hovered or inactive. 

I'm not sure still if it is bold or shadowy in Vertex-Maia. Maybe we can make some font bold by purpose to compare with what we have in these bloody buttons right now?

**Comment by Photon89** [comment] 2017-04-01 20:39
I have tried playing with colours to identify which options are referring to which state of the button. As far as I understand, what is inside lines 688-698
```
.inline-toolbar toolbutton > button, .primary-toolbar toolbar toolbutton > button {
...
}
```
is the default (and problematic) button state.

What is between lines 699 and 709 
```
.inline-toolbar toolbutton > button:hover, .primary-toolbar toolbar toolbutton > button:hover {
...
}
```

is the hovered button state, which is not problematic. Even worse, options in the first block seem to be inherited by the following blocks (unless explicitly overwritten therein). So I absolutely do not understand how it can happen that this blurry font is not inherited to the hovered state of the button (since there are no options in the second block which would explicitly overwrite anything from the first block)...

**Comment by oberon-manjaro** [comment] 2017-04-01 20:47
Yes, I know ... I spent two thirds of last night with this kind of things ... 😜 😆

**Comment by Photon89** [comment] 2017-04-01 20:51
😦 

Stupid questions: Are there still GTK engines in GTK3? If so, might this be a problem in the underlying engine?

**Comment by oberon-manjaro** [comment] 2017-04-01 20:59
No, they are gtk2.

**Comment by oberon-manjaro** [comment] 2017-04-01 22:48
It's even possible that the bold font there is an **atril** builtin setting ... Else I have no idea where it would come from.
In any case, since I have fixed my font config, it's just plain bold, no blurring, look:

![](http://imgur.com/enuBp8k.png)

**Comment by oberon-manjaro** [comment] 2017-04-01 22:55
Uhm. No, it's not... Just tried with mate menta theme - no bold font 😉 
gtk miracles ... ...

**Comment by oberon-manjaro** [comment] 2017-04-01 22:57
Arc-Maia works fine btw., or also Breath-gtk ...

**Comment by oberon-manjaro** [comment] 2017-04-01 23:06
You may also like TraditionalGreen. It's actually very similar to Manjaro green 😉 
I just really need a dark theme. Since I'm used to that bright themes really hurt my eyes ...

**Comment by Photon89** [comment] 2017-04-04 15:59
I tried the inspector thingy recommended by the Atril dev (start atril with `GTK_DEBUG=interactive atril`). Have found the two buttons, this is how they look like:

Blurry button: http://i.imgur.com/zyZeP3t.png
Inactive (non-blurry) button: http://i.imgur.com/V5Jbl3P.png

Some properties seem to differ, maybe something can be found by comparing the two? Also comparing to other themes? For example Adwaita which doesn't have this problem:

Active button: http://i.imgur.com/d4tC9VQ.png
Inactive button: http://i.imgur.com/tmuz5MH.png

By the way, I noticed that Eye of Mate (Mate's image viewer) also has this problem now...

edit: Looking at my own screenshots, I again stumble upon this text-shadow option which is only set to something other than "none" for the blurry button in Vertex Maia... And it stays in this debugging table even if I comment line 692 out!

edit2: Now I'm searching specifically for `text-shadow: 0 -1px rgba(0, 0, 0, 0.7)` and get many hits but so far commenting out none of them was successful. 

edit3: Yay, some of them was responsible for the issue! Now trying each of them separately.

**Comment by Photon89** [comment] 2017-04-04 16:24
Finally found it, it is necessary to remove line 1504. 😄

**Comment by oberon-manjaro** [comment] 2017-04-06 09:59
Interesting find! So there's a ``.drop-shadow``property, wow!
Just, removing that line (if you really mean the ``border-image:`` one) is certainly not a good way to fix it. It will change everything else listed under that category aswell.
It will just be necessary to redefine a designated css for ``.drop-shadow button:focus`` and remove that from the collection here...

**Comment by oberon-manjaro** [comment] 2017-04-06 10:18
Ah. Somehow I was in the wrong line. Things seem to shift in the installed theme... 😉 
Still I think we just need a separate definition.

**Comment by oberon-manjaro** [comment] 2017-04-06 10:20
I'll just change it to ``text-shadow: none;`` and lets see if it produces a problem anywhere else - normally a missing shadow shouldn't be a drama, anyway ;)
Thank again for your persistence!

**Comment by Photon89** [comment] 2017-04-06 12:47
Thanks for implementing the fix! If there is a better way to do it by a separate definition, it should probably be done like this. I never fiddled with GTK themes so I cannot judge. Simply removing this line fixed the problem for me and seemed to have no negative effects but this means nothing.

**Comment by Photon89** [comment] 2017-04-16 20:59
I noticed another little problem: The total number of pages (next to the "choose page number" text field) is invisible in Atril. Really sorry to bother, I hope, this is the very last problem. 😄

**Comment by Photon89** [comment] 2017-05-16 16:41
I think, I found a possible solution for the last problem (though I again cannot judge on its implications): If you change line 1129 from   

`color: #F3F5F3;`

to

`color: #000000;`

(or whatever color is used for the black font), the total page number appears again.

**Comment by oberon-manjaro** [comment] 2017-05-20 21:46
@Photon89 your fix doesn't seem to work for me ... :

![](http://imgur.com/ZITHKsH.png)

**Comment by oberon-manjaro** [comment] 2017-05-20 21:49
How about you just use **xreader** instead of **atril**? It's practically the same application but seems to treat theming slightly different: 😆 

![](http://imgur.com/cjqcCyv.png)

**Comment by Photon89** [comment] 2017-05-21 05:40
Thanks, it works for me now: http://storage7.static.itmages.com/i/17/0521/h_1495345101_4565548_854b210a79.png 👍  No idea why it doesn't for you. :)

**Comment by oberon-manjaro** [comment] 2017-05-21 22:50
It's working now since I have restarted Cinnamon 😄

**Comment by Photon89** [comment] 2017-05-22 07:32
Perfect, so we can put this issue to eternal rest finally! 😆

**Comment by oberon-manjaro** [comment] 2017-05-22 08:12
RIP
